export const hobbies = [
    "Reading"
    , "Writing"
    , "Cooking"
    , "Painting"
    , "Drawing"
    , "Cycling"
    , "Photography"
    , "Music"
    , "Movies"
    , "TV Series"
    , "Traveling"
    , "Football"
    , "Cricket"
    , "Yoga"
    , "Dancing"
    , "Acting"
    , "Singing"
    , "Gaming"
    , "DIY"
    , "Crafting"
    , "Gym"
    , "Camping"
    , "Volunteering"
    , "Hiking"
    , "Running"
    , "Swimming"
    , "Fishing"
    , "Gardening"
    , "Bird Watching"
    , "Astronomy"
    , "Collecting"
    , "Shopping"
    , "Fashion"
    , "Makeup"
    , "Hair Styling"
    , "Skincare"
    , "Vlogging"
    , "Podcasting"
]